# version: "3.9"
---
volumes:
  input:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/pipeline-data/input
      o: bind
  queue:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/pipeline-data/queue
      o: bind
  stems:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/pipeline-data/stems
      o: bind
  output:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/pipeline-data/output
      o: bind
  organized:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/pipeline-data/organized
      o: bind
  metadata:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/pipeline-data/metadata
      o: bind
  logs:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/pipeline-data/logs
      o: bind
# Note: redis_data stays named always (never bind-mounted)
