# version: "3.9"
---
services:
  tunnel:
    container_name: karaoke-pipeline-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks: [backend]

networks:
  backend:
    driver: bridge
