name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pip & wheel
        run: |
          python -m pip install --upgrade pip wheel
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Lint (flake8 or black)
        run: |
          pip install flake8
          flake8 .
      - name: (Optional) Run unit tests
        run: |
          echo "No unit tests yet"
      - name: (Optional) Build Docker image
        run: |
          docker build -t splitter .
