# version: "3.9"
services: {}

volumes:
  input:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/input
      o: bind
  queue:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/queue
      o: bind
  stems:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/stems
      o: bind
  output:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/output
      o: bind
  organized:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/organized
      o: bind
  metadata:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/metadata/json
      o: bind
  logs:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/logs
      o: bind

networks:
  backend:
    driver: bridge
