# version: "3.9"
---
services:
  packager:
    build: .
    environment:
      - PUID=1000
      - PGID=1000
      - INPUT_DIR=/input
      - OUTPUT_DIR=/output
      - REDIS_HOST=redis
    volumes:
      - ./input:/input
      - ./output:/output
    depends_on:
      - redis
    networks: [backend]

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks: [backend]

networks:
  backend:
    driver: bridge
